<?php
defined('BASEPATH') or exit('no direct script allowed');

class Respon extends CI_Controller{
	function __construct(){
		parent::__construct();
		$this->mysessioncheck->checkSession('id_admin','index.php/login');
	}

	

	function index(){
		$crud = new Grocery_CRUD_Extended();
		$this->load->config('grocery_crud');
 		//$this->config->set_item('grocery_crud_xss_clean', true);
		// $crud->unset_jquery();
		// $crud->unset_bootstrap();
		$crud->set_table('absen');
		$crud->unset_add();
		$crud->unset_edit();
		$crud->unset_read();
		$crud->unset_delete();
		$crud->where('tanggal',date('Y-m-d'));
		// $crud->callback_column('tanggal',array($this,'_callback_tanggal'));
		$crud->order_by('tanggal','asc');
		$output = $crud->render();
		$this->show('respon',$output);
	}

	function sup(){
		$crud = new Grocery_CRUD_Extended();
		$crud->set_model('modelgrocery');
		$this->load->config('grocery_crud');
		$crud->set_table('absen');
		$crud->columns(['nama','pangkat','keterangan','kondisi','tanggal','waktu']);
		$crud->basic_model->get_data();
		$crud->order_by('tanggal','asc');
		$output = $crud->render();
		$this->show('respon',$output);
	}

	public function laporan(){
		$this->load->model('ModelAbsen');
		$res['query'] = $this->ModelAbsen->getAll();

		$this->show('laporan',$res);
	}

	public function laporan_ropeg(){
		$this->load->Model('ModelAbsen');
		$data['nip'] = $this->ModelAbsen->getNIP();

		$this->show('laporan_ropeg',$data);
	}

	public function _callback_tanggal($value,$row){
		// $value = str_replace('/',$value,':'); 
		return $value;
	}

	function curl_request($nip){
      // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
      $ch = curl_init();

      curl_setopt($ch, CURLOPT_URL, 'https://absen.kemhan.go.id/versi3/absenisi/'.$nip);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


      $headers = array();
      $headers[] = 'Host: absen.kemhan.go.id';
      $headers[] = 'Connection: close';
      $headers[] = 'Accept-Encoding: gzip, deflate';
      $headers[] = 'User-Agent: okhttp/4.0.1';
      curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

      $result = curl_exec($ch);
      if (curl_errno($ch)) {
          echo 'Error:' . curl_error($ch);
      }
      curl_close($ch); 

      return $result; 
    }

    function imgRequest($nip){
	    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	  $ch = curl_init();

	  curl_setopt($ch, CURLOPT_URL, 'https://absen.kemhan.go.id/gambar/'.$nip.'.jpg');
	  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


	  $headers = array();
	  $headers[] = 'Host: absen.kemhan.go.id';
	  $headers[] = 'Connection: close';
	  $headers[] = 'Accept-Encoding: gzip, deflate';
	  $headers[] = 'User-Agent: okhttp/4.0.1';
	  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	  $result = curl_exec($ch);
	  if (curl_errno($ch)) {
	      echo 'Error:' . curl_error($ch);
	  }
	  curl_close($ch); 
	  return $result; 
	}
	
	function absenropeg(){
		$this->load->Model('ModelAbsen');
		$personil= $this->ModelAbsen->getNIP();

		$data = array();

		foreach($personil as $val){
			if($val['nip_nrp']!=''){
				$absen = json_decode($this->curl_request($val['nip_nrp']),TRUE); 
		  
			    foreach($absen as $rows){
			      $date=date('Y-m-d');	
			      if($rows['tanggal'] == $date && $rows['riwayat']=='Masuk' ){
			        
			        $imageData = base64_encode($this->imgRequest($val['nip_nrp']));
			        
			        $temp = array(
			        	'foto' => $imageData,
			        	'NIP' => $rows['nip'],
			        	'Nama'=> $val['nama'],
			        	'Jam' => $rows['jam'],
			        	'Status' => $rows['absensi'],
			        	'Kondisi' => $rows['kondisi'],
			        	'Lokasi' => $rows['lokasi'] 
			        );

			        //echo '<img src="data:image/jpeg;base64,'.$imageData.'"  style="max-width:70px;max-height:100px"><br>';
			        array_push($data,$temp);
			      }
			    }	
			}
		    
		 }
		echo json_encode($data);
	}

	public function show($page,$output=null){
		$this->load->view('base/header.php');
		$this->load->view('base/navbar.php');
		$this->load->view('base/sidebar.php');
		$this->load->view($page,$output);
		$this->load->view('base/footer.php');
	}
}

?>